package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public M setPname(java.lang.String pname) {
		set("pname", pname);
		return (M)this;
	}
	
	public java.lang.String getPname() {
		return getStr("pname");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("originalPrice", originalPrice);
		return (M)this;
	}
	
	public java.math.BigDecimal getOriginalPrice() {
		return get("originalPrice");
	}

	public M setTitleImg(java.lang.String titleImg) {
		set("title_img", titleImg);
		return (M)this;
	}
	
	public java.lang.String getTitleImg() {
		return getStr("title_img");
	}

	public M setHeadline(java.lang.String headline) {
		set("headline", headline);
		return (M)this;
	}
	
	public java.lang.String getHeadline() {
		return getStr("headline");
	}

	public M setSubtitle(java.lang.String subtitle) {
		set("subtitle", subtitle);
		return (M)this;
	}
	
	public java.lang.String getSubtitle() {
		return getStr("subtitle");
	}

	public M setIsHot(java.lang.Integer isHot) {
		set("isHot", isHot);
		return (M)this;
	}
	
	public java.lang.Integer getIsHot() {
		return getInt("isHot");
	}

	public M setIsRecommend(java.lang.Integer isRecommend) {
		set("isRecommend", isRecommend);
		return (M)this;
	}
	
	public java.lang.Integer getIsRecommend() {
		return getInt("isRecommend");
	}

	public M setScore(java.lang.Integer score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Integer getScore() {
		return getInt("score");
	}

	public M setCid(java.lang.Integer cid) {
		set("cid", cid);
		return (M)this;
	}
	
	public java.lang.Integer getCid() {
		return getInt("cid");
	}

}
