package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductimg<M extends BaseProductimg<M>> extends Model<M> implements IBean {

	public M setPimgID(java.lang.Integer pimgID) {
		set("pimgID", pimgID);
		return (M)this;
	}
	
	public java.lang.Integer getPimgID() {
		return getInt("pimgID");
	}

	public M setPimg(java.lang.String pimg) {
		set("pimg", pimg);
		return (M)this;
	}
	
	public java.lang.String getPimg() {
		return getStr("pimg");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

}
