package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCart<M extends BaseCart<M>> extends Model<M> implements IBean {

	public M setCartID(java.lang.Integer cartID) {
		set("cartID", cartID);
		return (M)this;
	}
	
	public java.lang.Integer getCartID() {
		return getInt("cartID");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

	public M setHeadline(java.lang.String headline) {
		set("headline", headline);
		return (M)this;
	}
	
	public java.lang.String getHeadline() {
		return getStr("headline");
	}

	public M setAmount(java.lang.String amount) {
		set("amount", amount);
		return (M)this;
	}
	
	public java.lang.String getAmount() {
		return getStr("amount");
	}

	public M setPrice(java.math.BigDecimal price) {
		set("price", price);
		return (M)this;
	}
	
	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

}
