package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAddress<M extends BaseAddress<M>> extends Model<M> implements IBean {

	public M setAddrId(java.lang.Integer addrId) {
		set("addrId", addrId);
		return (M)this;
	}
	
	public java.lang.Integer getAddrId() {
		return getInt("addrId");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setDetailAddr(java.lang.String detailAddr) {
		set("detailAddr", detailAddr);
		return (M)this;
	}
	
	public java.lang.String getDetailAddr() {
		return getStr("detailAddr");
	}

	public M setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
		return (M)this;
	}
	
	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public M setConsigneePhone(java.lang.String consigneePhone) {
		set("consigneePhone", consigneePhone);
		return (M)this;
	}
	
	public java.lang.String getConsigneePhone() {
		return getStr("consigneePhone");
	}

	public M setIsDefault(java.lang.Long isDefault) {
		set("isDefault", isDefault);
		return (M)this;
	}
	
	public java.lang.Long getIsDefault() {
		return getLong("isDefault");
	}

	public M setUid(java.lang.Integer uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

}
